In [1]:
from __future__ import annotations

from pathlib import Path

import mne
import numpy as np
import pandas as pd


PROJECT_ROOT: Path = Path("/home/russell/ssd/code/Topicos_Ciencia_Datos/Visual_Analytic_DEAP")

BDF_PATH: Path = PROJECT_ROOT / "dataset" / "raw" / "bdf" / "s28.bdf"
RATINGS_PATH: Path = PROJECT_ROOT / "dataset" / "raw" / "metadata" / "participant_ratings.xls"

ORIGINAL_SFREQ: float = 512.0

In [2]:
raw: mne.io.BaseRaw = mne.io.read_raw_bdf(
    BDF_PATH,
    preload=False,
    verbose=False,
)

print("BDF:", BDF_PATH)
print("sfreq:", raw.info["sfreq"])
print("n_times:", raw.n_times)
print("duration_sec:", raw.n_times / raw.info["sfreq"])
print("last channels:", raw.ch_names[-10:])

BDF: /home/russell/ssd/code/Topicos_Ciencia_Datos/Visual_Analytic_DEAP/dataset/raw/bdf/s28.bdf
sfreq: 512.0
n_times: 1805824
duration_sec: 3527.0
last channels: ['EXG7', 'EXG8', 'GSR1', 'GSR2', 'Erg1', 'Erg2', 'Resp', 'Plet', 'Temp', '']

/tmp/ipykernel_21774/3264834722.py:1: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw: mne.io.BaseRaw = mne.io.read_raw_bdf(
/tmp/ipykernel_21774/3264834722.py:1: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw: mne.io.BaseRaw = mne.io.read_raw_bdf(

In [3]:
def normalize_event_codes(event_codes: np.ndarray) -> np.ndarray:
    normalized_codes: np.ndarray = event_codes.copy().astype(int)
    mask: np.ndarray = normalized_codes >= 1638144
    normalized_codes[mask] = normalized_codes[mask] - 1638144
    return normalized_codes


for channel_name in raw.ch_names[-10:]:
    try:
        events: np.ndarray = mne.find_events(
            raw,
            stim_channel=channel_name,
            shortest_event=1,
            verbose=False,
        )

        if events.size == 0:
            continue

        normalized_codes: np.ndarray = normalize_event_codes(events[:, 2])
        unique_codes: np.ndarray
        counts: np.ndarray
        unique_codes, counts = np.unique(normalized_codes, return_counts=True)

        print("\nCHANNEL:", repr(channel_name))
        print("num_events:", len(events))
        print(dict(zip(unique_codes.tolist(), counts.tolist())))

    except Exception as error:
        print("ERROR:", repr(channel_name), error)

CHANNEL: 'GSR1'
num_events: 864849

In [4]:
STATUS_CHANNEL: str = ""  # cambia si el canal correcto tiene otro nombre

events: np.ndarray = mne.find_events(
    raw,
    stim_channel=STATUS_CHANNEL,
    shortest_event=1,
    verbose=False,
)

events[:, 2] = normalize_event_codes(events[:, 2])

relevant_events: np.ndarray = events[np.isin(events[:, 2], [3, 4, 5])]

df_events: pd.DataFrame = pd.DataFrame(
    {
        "sample": relevant_events[:, 0].astype(int),
        "time_sec": relevant_events[:, 0] / ORIGINAL_SFREQ,
        "code": relevant_events[:, 2].astype(int),
    }
)

print("counts:")
print(df_events["code"].value_counts().sort_index())

display(df_events.head(40))
display(df_events.tail(40))

counts:
code
3    39
4    37
5    39
Name: count, dtype: int64

    sample     time_sec  code
0    14391    28.107422     3
1    25626    50.050781     5
2    41049    80.173828     5
3   109786   214.425781     3
4   112371   219.474609     4
5   143140   279.570312     5
6   153863   300.513672     3
7   156439   305.544922     4
8   187191   365.607422     5
9   196497   383.783203     3
10  199082   388.832031     4
11  229825   448.876953     5
12  237639   464.138672     3
13  240224   469.187500     4
14  270967   529.232422     5
15  278167   543.294922     3
16  280743   548.326172     4
17  311486   608.371094     5
18  320742   626.449219     3
19  323327   631.498047     4
20  354062   691.527344     5
21  363846   710.636719     3
22  366430   715.683594     4
23  397182   775.746094     5
24  406915   794.755859     3
25  409500   799.804688     4
26  440235   859.833984     5
27  446829   872.712891     3
28  449405   877.744141     4
29  480157   937.806641     5
30  488867   954.818359     3
31  491451   959.865234     4
32  522195  1019.912109     5
33  530776  1036.671875     3
34  533361  1041.720703     4
35  564104  1101.765625     5
36  575748  1124.507812     3
37  578333  1129.556641     4
38  609076  1189.601562     5
39  619816  1210.578125     3

      sample     time_sec  code
75   1260519  2461.951172     5
76   1266422  2473.480469     3
77   1269007  2478.529297     4
78   1299750  2538.574219     5
79   1309193  2557.017578     3
80   1311778  2562.066406     4
81   1342522  2622.113281     5
82   1350037  2636.791016     3
83   1352622  2641.839844     4
84   1383365  2701.884766     5
85   1389839  2714.529297     3
86   1392416  2719.562500     4
87   1423176  2779.640625     5
88   1433958  2800.699219     3
89   1436543  2805.748047     4
90   1467287  2865.794922     5
91   1475058  2880.972656     3
92   1477634  2886.003906     4
93   1508386  2946.066406     5
94   1514536  2958.078125     3
95   1517112  2963.109375     4
96   1547864  3023.171875     5
97   1555533  3038.150391     3
98   1558109  3043.181641     4
99   1588861  3103.244141     5
100  1594346  3113.957031     3
101  1596931  3119.005859     4
102  1627674  3179.050781     5
103  1633825  3191.064453     3
104  1636401  3196.095703     4
105  1667153  3256.158203     5
106  1672979  3267.537109     3
107  1675564  3272.585938     4
108  1706307  3332.630859     5
109  1714710  3349.042969     3
110  1717294  3354.089844     4
111  1748038  3414.136719     5
112  1754683  3427.115234     3
113  1757268  3432.164062     4
114  1788020  3492.226562     5

In [5]:
ratings_df: pd.DataFrame = pd.read_excel(RATINGS_PATH)

s28_ratings: pd.DataFrame = ratings_df[
    ratings_df["Participant_id"] == 28
].copy()

s28_ratings = s28_ratings.sort_values("Trial").reset_index(drop=True)
s28_ratings["start_sec"] = s28_ratings["Start_time"] / 10000

event4_df: pd.DataFrame = df_events[df_events["code"] == 4].copy()
event4_df = event4_df.reset_index(drop=True)
event4_df["event4_index"] = event4_df.index + 1

print("ratings rows:", len(s28_ratings))
print("event 4 rows:", len(event4_df))

display(s28_ratings[["Trial", "Experiment_id", "Start_time", "start_sec"]].head(10))
display(event4_df.head(10))
display(s28_ratings[["Trial", "Experiment_id", "Start_time", "start_sec"]].tail(10))
display(event4_df.tail(10))

ratings rows: 40
event 4 rows: 37

   Trial  Experiment_id  Start_time  start_sec
0      1             12     1903620   190.3620
1      2             34     2764551   276.4551
2      3              2     3597195   359.7195
3      4              7     4400765   440.0765
4      5             21     5192388   519.2388
5      6             22     6023875   602.3875
6      7             32     6865767   686.5767
7      8             33     7706955   770.6955
8      9             15     8486596   848.6596
9     10             17     9307588   930.7588

   sample    time_sec  code  event4_index
0  112371  219.474609     4             1
1  156439  305.544922     4             2
2  199082  388.832031     4             3
3  240224  469.187500     4             4
4  280743  548.326172     4             5
5  323327  631.498047     4             6
6  366430  715.683594     4             7
7  409500  799.804688     4             8
8  449405  877.744141     4             9
9  491451  959.865234     4            10

    Trial  Experiment_id  Start_time  start_sec
30     31             20    27553255  2755.3255
31     32             13    28414898  2841.4898
32     33             31    29217685  2921.7685
33     34             39    29988757  2998.8757
34     35             40    30789484  3078.9484
35     36              5    31547488  3154.7488
36     37             29    32318627  3231.8627
37     38             19    33083309  3308.3309
38     39             28    33898368  3389.8368
39     40             36    34679087  3467.9087

     sample     time_sec  code  event4_index
27  1392416  2719.562500     4            28
28  1436543  2805.748047     4            29
29  1477634  2886.003906     4            30
30  1517112  2963.109375     4            31
31  1558109  3043.181641     4            32
32  1596931  3119.005859     4            33
33  1636401  3196.095703     4            34
34  1675564  3272.585938     4            35
35  1717294  3354.089844     4            36
36  1757268  3432.164062     4            37

In [6]:
comparison_rows: list[dict[str, float | int]] = []

for rating_index, rating_row in s28_ratings.iterrows():
    trial: int = int(rating_row["Trial"])
    rating_start_sec: float = float(rating_row["start_sec"])

    for event_index, event_row in event4_df.iterrows():
        event4_time_sec: float = float(event_row["time_sec"])
        diff_sec: float = event4_time_sec - rating_start_sec

        if 0.0 <= diff_sec <= 80.0:
            comparison_rows.append(
                {
                    "trial": trial,
                    "rating_index": rating_index + 1,
                    "event4_index": event_index + 1,
                    "rating_start_sec": rating_start_sec,
                    "event4_time_sec": event4_time_sec,
                    "diff_sec": diff_sec,
                }
            )

comparison_df: pd.DataFrame = pd.DataFrame(comparison_rows)

display(comparison_df.head(50))
display(comparison_df.tail(50))

,trial,rating_index,event4_index,rating_start_sec,event4_time_sec,diff_sec
0,1,1,1,190.3620,219.474609,29.112609
1,2,2,2,276.4551,305.544922,29.089822
2,3,3,3,359.7195,388.832031,29.112531
3,4,4,4,440.0765,469.187500,29.111000
4,5,5,5,519.2388,548.326172,29.087372
5,6,6,6,602.3875,631.498047,29.110547
6,7,7,7,686.5767,715.683594,29.106894
7,8,8,8,770.6955,799.804688,29.109187
8,9,9,9,848.6596,877.744141,29.084541
9,10,10,10,930.7588,959.865234,29.106434
10,11,11,11,1012.6142,1041.720703,29.106503
11,12,12,12,1100.4502,1129.556641,29.106441
12,13,13,13,1186.5276,1215.609375,29.081775
13,14,14,14,1271.9651,1301.046875,29.081775
14,15,15,15,1355.1534,1384.234375,29.080975
15,16,16,16,1432.6698,1461.775391,29.105591
16,17,17,17,1512.5163,1541.595703,29.079403
17,18,18,18,1594.5990,1623.701172,29.102172
18,19,19,19,1677.5717,1706.671875,29.100175
19,20,20,20,1759.4821,1788.560547,29.078447
20,21,21,21,1855.6262,1884.726562,29.100363
21,22,22,22,1940.0371,1969.113281,29.076181
22,23,23,23,2023.5357,2052.634766,29.099066
23,27,27,25,2437.6444,2478.529297,40.884897
24,28,28,26,2514.2677,2562.066406,47.798706
25,29,29,27,2597.8062,2641.839844,44.033644
26,30,30,28,2677.5788,2719.562500,41.983700
27,31,31,29,2755.3255,2805.748047,50.422547
28,32,32,30,2841.4898,2886.003906,44.514106
29,33,33,31,2921.7685,2963.109375,41.340875
30,34,34,32,2998.8757,3043.181641,44.305941
31,35,35,33,3078.9484,3119.005859,40.057459
32,36,36,34,3154.7488,3196.095703,41.346903
33,37,37,35,3231.8627,3272.585938,40.723237
34,38,38,36,3308.3309,3354.089844,45.758944
35,39,39,37,3389.8368,3432.164062,42.327262

,trial,rating_index,event4_index,rating_start_sec,event4_time_sec,diff_sec
0,1,1,1,190.3620,219.474609,29.112609
1,2,2,2,276.4551,305.544922,29.089822
2,3,3,3,359.7195,388.832031,29.112531
3,4,4,4,440.0765,469.187500,29.111000
4,5,5,5,519.2388,548.326172,29.087372
5,6,6,6,602.3875,631.498047,29.110547
6,7,7,7,686.5767,715.683594,29.106894
7,8,8,8,770.6955,799.804688,29.109187
8,9,9,9,848.6596,877.744141,29.084541
9,10,10,10,930.7588,959.865234,29.106434
10,11,11,11,1012.6142,1041.720703,29.106503
11,12,12,12,1100.4502,1129.556641,29.106441
12,13,13,13,1186.5276,1215.609375,29.081775
13,14,14,14,1271.9651,1301.046875,29.081775
14,15,15,15,1355.1534,1384.234375,29.080975
15,16,16,16,1432.6698,1461.775391,29.105591
16,17,17,17,1512.5163,1541.595703,29.079403
17,18,18,18,1594.5990,1623.701172,29.102172
18,19,19,19,1677.5717,1706.671875,29.100175
19,20,20,20,1759.4821,1788.560547,29.078447
20,21,21,21,1855.6262,1884.726562,29.100363
21,22,22,22,1940.0371,1969.113281,29.076181
22,23,23,23,2023.5357,2052.634766,29.099066
23,27,27,25,2437.6444,2478.529297,40.884897
24,28,28,26,2514.2677,2562.066406,47.798706
25,29,29,27,2597.8062,2641.839844,44.033644
26,30,30,28,2677.5788,2719.562500,41.983700
27,31,31,29,2755.3255,2805.748047,50.422547
28,32,32,30,2841.4898,2886.003906,44.514106
29,33,33,31,2921.7685,2963.109375,41.340875
30,34,34,32,2998.8757,3043.181641,44.305941
31,35,35,33,3078.9484,3119.005859,40.057459
32,36,36,34,3154.7488,3196.095703,41.346903
33,37,37,35,3231.8627,3272.585938,40.723237
34,38,38,36,3308.3309,3354.089844,45.758944
35,39,39,37,3389.8368,3432.164062,42.327262

In [7]:
direct_rows: list[dict[str, float | int | None]] = []

max_len: int = max(len(s28_ratings), len(event4_df))

for index in range(max_len):
    rating_start_sec: float | None = None
    event4_time_sec: float | None = None
    diff_sec: float | None = None

    if index < len(s28_ratings):
        rating_start_sec = float(s28_ratings.iloc[index]["start_sec"])

    if index < len(event4_df):
        event4_time_sec = float(event4_df.iloc[index]["time_sec"])

    if rating_start_sec is not None and event4_time_sec is not None:
        diff_sec = event4_time_sec - rating_start_sec

    direct_rows.append(
        {
            "index": index + 1,
            "trial": int(s28_ratings.iloc[index]["Trial"]) if index < len(s28_ratings) else None,
            "rating_start_sec": rating_start_sec,
            "event4_time_sec": event4_time_sec,
            "diff_sec": diff_sec,
        }
    )

direct_df: pd.DataFrame = pd.DataFrame(direct_rows)

display(direct_df)

    index  trial  rating_start_sec  event4_time_sec    diff_sec
0       1      1          190.3620       219.474609   29.112609
1       2      2          276.4551       305.544922   29.089822
2       3      3          359.7195       388.832031   29.112531
3       4      4          440.0765       469.187500   29.111000
4       5      5          519.2388       548.326172   29.087372
5       6      6          602.3875       631.498047   29.110547
6       7      7          686.5767       715.683594   29.106894
7       8      8          770.6955       799.804688   29.109187
8       9      9          848.6596       877.744141   29.084541
9      10     10          930.7588       959.865234   29.106434
10     11     11         1012.6142      1041.720703   29.106503
11     12     12         1100.4502      1129.556641   29.106441
12     13     13         1186.5276      1215.609375   29.081775
13     14     14         1271.9651      1301.046875   29.081775
14     15     15         1355.1534      1384.234375   29.080975
15     16     16         1432.6698      1461.775391   29.105591
16     17     17         1512.5163      1541.595703   29.079403
17     18     18         1594.5990      1623.701172   29.102172
18     19     19         1677.5717      1706.671875   29.100175
19     20     20         1759.4821      1788.560547   29.078447
20     21     21         1855.6262      1884.726562   29.100363
21     22     22         1940.0371      1969.113281   29.076181
22     23     23         2023.5357      2052.634766   29.099066
23     24     24         2107.4241      2401.906250  294.482150
24     25     25         2188.6296      2478.529297  289.899697
25     26     26         2270.1010      2562.066406  291.965406
26     27     27         2437.6444      2641.839844  204.195444
27     28     28         2514.2677      2719.562500  205.294800
28     29     29         2597.8062      2805.748047  207.941847
29     30     30         2677.5788      2886.003906  208.425106
30     31     31         2755.3255      2963.109375  207.783875
31     32     32         2841.4898      3043.181641  201.691841
32     33     33         2921.7685      3119.005859  197.237359
33     34     34         2998.8757      3196.095703  197.220003
34     35     35         3078.9484      3272.585938  193.637537
35     36     36         3154.7488      3354.089844  199.341044
36     37     37         3231.8627      3432.164062  200.301362
37     38     38         3308.3309              NaN         NaN
38     39     39         3389.8368              NaN         NaN
39     40     40         3467.9087              NaN         NaN

In [8]:
# Zona donde la correspondencia se rompe: entre trial 23 y 27 aprox.
window_events: pd.DataFrame = df_events[
    (df_events["time_sec"] >= 2000)
    & (df_events["time_sec"] <= 2500)
].copy()

display(window_events)

     sample     time_sec  code
68  1038938  2029.175781     5
69  1048365  2047.587891     3
70  1050949  2052.634766     4
71  1081684  2112.664062     5
72  1091315  2131.474609     3
73  1227191  2396.857422     3
74  1229776  2401.906250     4
75  1260519  2461.951172     5
76  1266422  2473.480469     3
77  1269007  2478.529297     4

In [10]:
display(
    s28_ratings.loc[20:28, ["Trial", "Experiment_id", "Start_time", "start_sec"]]
)

    Trial  Experiment_id  Start_time  start_sec
20     21             37    18556262  1855.6262
21     22             16    19400371  1940.0371
22     23              4    20235357  2023.5357
23     24             26    21074241  2107.4241
24     25             25    21886296  2188.6296
25     26             14    22701010  2270.1010
26     27             23    24376444  2437.6444
27     28              8    25142677  2514.2677
28     29             10    25978062  2597.8062

In [11]:
# Offset estable observado en los primeros 23 trials.
stable_offset: float = float(direct_df.loc[0:22, "diff_sec"].median())

print("stable_offset:", stable_offset)

s28_check: pd.DataFrame = s28_ratings.copy()
s28_check["estimated_event4_sec"] = s28_check["start_sec"] + stable_offset
s28_check["estimated_event5_sec"] = s28_check["estimated_event4_sec"] + 60.0
s28_check["fits_in_bdf"] = s28_check["estimated_event5_sec"] <= (raw.n_times / raw.info["sfreq"])

display(
    s28_check[["Trial", "Experiment_id", "start_sec", "estimated_event4_sec", "estimated_event5_sec", "fits_in_bdf"]]
)

stable_offset: 29.100362500000074

,Trial,Experiment_id,start_sec,estimated_event4_sec,estimated_event5_sec,fits_in_bdf
0,1,12,190.3620,219.462363,279.462363,True
1,2,34,276.4551,305.555463,365.555463,True
2,3,2,359.7195,388.819863,448.819863,True
3,4,7,440.0765,469.176863,529.176863,True
4,5,21,519.2388,548.339163,608.339163,True
5,6,22,602.3875,631.487863,691.487863,True
6,7,32,686.5767,715.677063,775.677063,True
7,8,33,770.6955,799.795863,859.795863,True
8,9,15,848.6596,877.759963,937.759963,True
9,10,17,930.7588,959.859163,1019.859163,True
10,11,30,1012.6142,1041.714563,1101.714563,True
11,12,35,1100.4502,1129.550563,1189.550563,True
12,13,3,1186.5276,1215.627962,1275.627962,True
13,14,24,1271.9651,1301.065462,1361.065462,True
14,15,1,1355.1534,1384.253762,1444.253762,True
15,16,18,1432.6698,1461.770162,1521.770162,True
16,17,38,1512.5163,1541.616663,1601.616663,True
17,18,11,1594.5990,1623.699363,1683.699363,True
18,19,6,1677.5717,1706.672063,1766.672063,True
19,20,9,1759.4821,1788.582463,1848.582463,True
20,21,37,1855.6262,1884.726562,1944.726562,True
21,22,16,1940.0371,1969.137463,2029.137463,True
22,23,4,2023.5357,2052.636062,2112.636062,True
23,24,26,2107.4241,2136.524463,2196.524463,True
24,25,25,2188.6296,2217.729963,2277.729963,True
25,26,14,2270.1010,2299.201362,2359.201362,True
26,27,23,2437.6444,2466.744763,2526.744763,True
27,28,8,2514.2677,2543.368062,2603.368062,True
28,29,10,2597.8062,2626.906563,2686.906563,True
29,30,27,2677.5788,2706.679162,2766.679162,True
30,31,20,2755.3255,2784.425863,2844.425863,True
31,32,13,2841.4898,2870.590162,2930.590162,True
32,33,31,2921.7685,2950.868863,3010.868863,True
33,34,39,2998.8757,3027.976062,3087.976062,True
34,35,40,3078.9484,3108.048763,3168.048763,True
35,36,5,3154.7488,3183.849162,3243.849162,True
36,37,29,3231.8627,3260.963062,3320.963062,True
37,38,19,3308.3309,3337.431263,3397.431263,True
38,39,28,3389.8368,3418.937163,3478.937163,True
39,40,36,3467.9087,3497.009063,3557.009063,False